### PR TITLE
Bump up OpenSearch to version 2.1.0

### PR DESCRIPTION
**Pull request by systemosyn**
Bump up OpenSearch to version 2.1.0

P.S: this is my first contribution don't hesitate to tell me if other requirements are needed for this to be merged.

### CODE REVIEW

**Review by willyborankin — CHANGES_REQUESTED** [review]
Thank you! 
You need to configure signature for your commit. How to do it you can read here:
https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
and how to config:
https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#misc
LGTM

**Comment by systemosyn** [comment]
Thanks a lot @willyborankin, I launched the `git secrets --install && git secrets --register-aws` before the signedoff commit was pushed, tell me if there's still issues and sorry for this mistake.

**Comment by willyborankin** [comment]
> Thanks a lot @willyborankin, I launched the `git secrets --install && git secrets --register-aws` before the signedoff commit was pushed, tell me if there's still issues and sorry for this mistake.

No problem. now you need to do this:
```git commit --amend  --signoff  -S && git push -f ```

**Review by willyborankin — CHANGES_REQUESTED** [review]
@systemosyn Could you please squash your 5 commits?

**Comment by systemosyn** [comment]
It is done, tell me if everything is OK.

**Comment by willyborankin** [comment]
will merge it a bit later

**Pull request merged**
